[package]
name = "ludo-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
ludo-ai = { path = "../ludo-ai" }
ludo-application = { path = "../ludo-application" }
ludo-domain = { path = "../ludo-domain" }
ludo-infrastructure = { path = "../ludo-infrastructure" }
ludo-presentation = { path = "../ludo-presentation" }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
