[package]
name = "ludo-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ludo-ai = { path = "../ludo-ai", default-features = false }
ludo-application = { path = "../ludo-application" }
ludo-domain = { path = "../ludo-domain" }
ludo-presentation = { path = "../ludo-presentation" }
serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true

[lints]
workspace = true
